.TH rf 1

.SH NAME
rf \- a tiny and simple file finder

.SH SYNOPSIS
.SY rf
.OP \-d directory
.OP \-c config
.OP \-lsvw
.OP pattern ...

.SH DESCRIPTION
\fBrf\fR will find files or directories based on one or more glob (or optionally
substring) patterns, while respecting any ignore rules in \fBrfignore\fR files.

.SH OPTIONS
.TP
.BI \-d directory
Search from specified directory, otherwise defaults to current working directory.
.
.TP
.BI \-c config
Override config file location.
.
.TP
.BI \-l count
Limit to specified matches count.
.
.TP
.B \-s
Match using substrings instead of globs.
.
.TP
.B \-v
Invert matches.
.
.TP
.B \-w
Match wholename, including path.

.SH SEE ALSO
.BR rfignore (5),
.BR rfconfig (5)

.SH COPYRIGHT
Copyright \(co 2019, 2020 Rory Bradford <roryrjb@gmail.com>.
