.TH rf 1

.SH NAME
rf \- a tiny and simple file finder

.SH SYNOPSIS
.SY rf
.OP \-lvSU
.OP pattern ...

.SH DESCRIPTION
.B rf
will find files or directories based on one or more glob patterns.

.SH OPTIONS
.TP
.B \-v
Invert matches.
.
.TP
.BI \-l count
Limit to specified matches count.
.
.TP
.B \-U
Unlink matched file. Cannot be used with any other options.
.
.TP
.BI \-S command
Run shell command over each file. A %s will be replaced with the relative
path to the current file. Cannot be used with any other options.

.SH COPYRIGHT
Copyright \(co 2020 Rory Bradford <roryrjb@gmail.com>.
