.TH rfconfig 5

.SH NAME
rfconfig \- configure rf behaviour

.SH SYNOPSIS
$XDG_CONFIG_HOME/rf/config

.SH DESCRIPTION
An \fBrfconfig\fR file is used to override default behaviour and configure options.

.SH FORMAT
The config file format is very simple. Comments are only available for a whole
line and start with #. Any lines that begin with a space are ignored.
Each valid config line consists of a key value pair with the key and value
separated by an = character and optionally a single space either side. Additional
spaces will become part of either the key and/or value.

.SH OPTIONS
.TP
.B symlinks
Read symlinks (value: "true" or "false")
.
.TP
.B wholename
Match whole path (value "true" or "false")
.
.TP
.B limit
Limit amount of results (value: a positive integer)
.
.TP
.B wildcard
Define a custom wildcard character, used in place of * (value: a single ascii character)
.
.TP
.B unmatched error
Exit with non-zero exit code if there were no matches

.SH COPYRIGHT
Copyright \(co 2019, 2020 Rory Bradford <roryrjb@gmail.com>.
