#!/bin/sh

set -e

files=
edit=

EDITOR=${EDITOR:-vim}

while getopts 'ef' opt; do
    case $opt in
        e) edit=1; shift ;;
        f) files=1; shift ;;
    esac
done

if [ "$files" ]; then
    rf '*' | xargs grep -Ir "$1" | awk -F':' '{print $1}' | sort | uniq
elif [ "$edit" ]; then
    $EDITOR $(rf '*' | xargs grep -Ir "$1" | awk -F':' '{print $1}' | sort | uniq)
else
    rf '*' | xargs grep -Ir "$1"
fi
